---
name: Apache2-Filter-Minifier-JavaScript
version: 1.05
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: JS minifying output filter
license: perl
resources:
  license: ~
requires:
  JavaScript::Minifier: 0
  Time::HiRes: 0
  mod_perl2: 2
  perl: 5.6.0
build_requires:
  Apache::Test: 1.12
recommends:
  JavaScript::Minifier::XS: 0
provides:
  Apache2::Filter::Minifier::JavaScript:
    file: lib/Apache2/Filter/Minifier/JavaScript.pm
    version: 1.05
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
configure_requires:
  Apache::Test: 1.12
